name: Test and Lint

on:
  release:
    branches:
      - main
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn
      - run: yarn run build:plugin
      - run: cd packages/orbiton && yarn link
      - run: cd ../../ && yarn link orbiton
      - run: yarn test
  lint:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn
        # linting Orbiton
      - run: yarn run lint
        # linting babel plugin
      - run: yarn run lint:plugin
